# Generated by Django 5.0.7 on 2025-02-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0003_remove_productmodel_body_productmodel_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('image', models.ImageField(upload_to='one_models/', verbose_name='Rasmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
            ],
        ),
    ]
