# Generated by Django 5.0.7 on 2025-02-10 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0004_onemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onemodel',
            name='created_at',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='one_models', to='mebel.onemodel', verbose_name='Mahsulot'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onemodel',
            name='image',
            field=models.ImageField(upload_to='products/', verbose_name='Rasmi'),
        ),
    ]
